/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_StaticInit */

#ifndef _Included_jni_StaticInit
#define _Included_jni_StaticInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_StaticInit
 * Method:    initHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jni_StaticInit_initHandle
  (JNIEnv *, jobject);

/*
 * Class:     jni_StaticInit
 * Method:    doSomething
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_StaticInit_doSomething
  (JNIEnv *, jobject);

/*
 * Class:     jni_StaticInit
 * Method:    releaseHandle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_StaticInit_releaseHandle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
